// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4Eg04pnCgD6-E2GfFYK9-wo3Gz60J-F0',
    appId: '1:671357529791:android:394a2725dccb9695c1200a',
    messagingSenderId: '671357529791',
    projectId: 'blogapp-3506b',
    storageBucket: 'blogapp-3506b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGqxxi6-Tr-EozKpylJeSpHORgDvPp00U',
    appId: '1:671357529791:ios:e767e1889353b8b7c1200a',
    messagingSenderId: '671357529791',
    projectId: 'blogapp-3506b',
    storageBucket: 'blogapp-3506b.firebasestorage.app',
    iosBundleId: 'com.example.blogApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8iFpQLFZty7pGhQR1nPGBPYYckp7jKPQ',
    appId: '1:671357529791:web:7bb8379b7e1d7b94c1200a',
    messagingSenderId: '671357529791',
    projectId: 'blogapp-3506b',
    authDomain: 'blogapp-3506b.firebaseapp.com',
    storageBucket: 'blogapp-3506b.firebasestorage.app',
  );
}
